spring:
  application:
    name: movieflix

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostrgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
